### ISSUE TITLE
Dependency on "nightwatch" has gone missing

### ISSUE THREAD

**Issue by ghost** [gextech/nwrun#4]
Version 0.2.0 of `nwrun` fails with `Error: Cannot find module 'nightwatch'`.

Apparently, the nightwatch sub dependency is no longer being installed.

My guess is that this has to do with a recent change to the `package.json` where nightwatch was moved to the `devDependencies`: https://github.com/gextech/nwrun/commit/4e4a29a30f0fd3ad0a20d253177b5a2eb1a23f9d.

Since `grunt-nightwatch` will install the bleeding-edge version of `nwrun`, our builds that depend on the former are now failing.

We've temporarily fixed the issue by adding an explicit dependency on nwrun v0.1.0 to our npm config, which is rather hacky.

If you can confirm that this is a configuration bug, I'd be happy if you could publish a fix (and possibly make the version requirement in the `grunt-nightwatch` config a bit more strict?). Thanks a lot.

**Comment by pateketrueke** [comment]
Just by adding `nightwatch` to your `dependencies` list would do the trick, I've added a note for that breaking change, sorry.

**Comment by pateketrueke** [comment]
See: https://github.com/gextech/grunt-nightwatch/issues/63

Some people doesn't wants `nightwatch` to be installed as dependency...

And actually I agree, adding `nightwatch` in your `package.json` or `npm link nightwatch` from global installations are the perfect fit for both issues.
