### ISSUE TITLE
Can't specify environment when using test workers

### ISSUE THREAD

**Issue by ericmacfa** [gextech/nwrun#5]
**Disclaimer:** Sorry for the long post! I'm trying to include as much helpful information as possible.
#### Background
-  I'm using grunt-nightwatch, but the issue seems to come from nwrun (see debugging section)
-  I have two tests in my `tests` directory (FirstTest.js and SecondTest.js)
-  I have `"test_workers" : {"enabled" : true, "workers" : "auto"}` in my Nightwatch config (see attached GruntFile
-  I have two environments aside from default, one is a chrome environment, the other is an IE environment
-  Attached Files (all as .txt due to upload restrictions:
  -  My [GruntFile](https://github.com/gextech/nwrun/files/345334/GruntFile.txt)
  -  My [package.json](https://github.com/gextech/nwrun/files/345335/package.txt) (might be helpful for reproducing)
  -  [Full copy of stdout](https://github.com/gextech/nwrun/files/345336/out-pre-comment.txt) without commenting out code (see debugging section)
  -  [Full copy of stdout](https://github.com/gextech/nwrun/files/345337/out-post-comment.txt) after commenting out code (see debugging section)
#### Issue Description

When I try to run tests in the `ie` environment (`grunt nightwatch:ie`) the tests run in the `default` environment instead (you can tell it's `default` because it opens in chrome and the window doesn't start maximized).

When I comment out `"test_workers" : {"enabled" : true, "workers" : "auto"}` the tests run in the `ie` environment as expected.

Can anyone provide any help with this issue? (I tried a little debugging below)
#### My Debugging

I took the liberty of digging around in the code from `spawn.js` and noticed the below code (lines 40-46):

```
Object.keys(argv).forEach(function(key) {
    if (key === 'env' && a['parallel-mode'] === true) {
        return;
    }

    a[key] = argv[key];
});
```

I added `console.log(JSON.stringify(a, null, 4));` after the above function. When running `grunt nightwatch:sauce` on the command line, I saw this before child processes were created:

```
{
    "_": [
        "nightwatch:sauce"
    ],
    "config": "__NWRUN_FAKED_CONFIG_BECAUSE_YOLO__0.3433402725495398",
    "c": "./nightwatch.json",
    "output": "tests_output",
    "o": "tests_output",
    "reporter": "junit",
    "r": "junit",
    "env": "ie",
    "e": "default",
    "filter": "",
    "f": "",
    "tag": "",
    "a": "",
    "$0": "path_to_grunt"
}
```

then this for each of the child processes (with different values for `test` and `t`

```
{
    "_": [
        "nightwatch:sauce"
    ],
    "test": "path_to_tests_dir\\FirstTest",
    "t": "path_to_tests_dir\\FirstTest",
    "test-worker": true,
    "parallel-mode": true,
    "config": "__NWRUN_FAKED_CONFIG_BECAUSE_YOLO__0.5414587843697518",
    "c": "./nightwatch.json",
    "output": "tests_output",
    "o": "tests_output",
    "reporter": "junit",
    "r": "junit",
    "env": "default",
    "e": "default",
    "filter": "",
    "f": "",
    "tag": "",
    "a": "",
    "$0": "path_to_grunt"
}
```

Taking special notice of the difference in values for `"env"`, it looks like the test environment is not passed on to the child processes as expected...but when I commented out the below code (from above reference):

```
if (key === 'env' && a['parallel-mode'] === true) {
    return;
}
```

the value for `"env"` was `"ie"` in the pre-child and child logs, and the tests ran in the expected browser.
##### Question after debugging

I'm sure there's a good reason for why those three lines of code exist, can anyone help me find a more elegant workaround for the larger issue that I mentioned?

Thanks a bunch!

**Comment by pateketrueke** [comment]
> I'm sure there's a good reason for why those three lines of code exist, can anyone help me find a more elegant workaround for the larger issue that I mentioned?

Actually I just copied those lines from the original Nightwatch source-code without fully understanding, sorry for that.

Now I understand your issue, some way we should normalize those argvs before calling `nightwatch.runner`, so let me see what can I do.

Thanks for your feedback!

**Comment by ericmacfa** [comment]
Awesome! Thanks for the quick reply and for taking a look!

**Comment by pateketrueke** [comment]
Hi again!

I've released a patch using `nightwatch.runner()` now, also all argvs are normalized properly.

Please test on your own environments, the integration is more straight forward and it should work the same way as Nightwatch's CLI.
