### ISSUE TITLE
nwrun Fails when "test_workers"->"enabled:true" 

### ISSUE THREAD

**Issue by dim912** [gextech/nwrun#7]
we are looking to use nwrun. we faced below issue.

I am looking to use "test_workers" nightawtch property. But nwrun fails when I set this property with enabled as true. 
Ex : "test_workers": { "enabled": true, "workers": "auto" }, 

Object that is passed to nwrun
-----------------------------------
{
 standalone: true,
  "src_folders": [
    "tests/",
  ],
  "output_folder": "./testReports", // reports (test outcome) output by nightwatch
  "test_workers": { "enabled": true, "workers": "auto" } // perform tests in parallel
}

output
---------
Starting selenium server in parallel mode... started - PID:  10084

Started child process for: google

  >> google finished.

Above is tested with the google.js ci-test example provided. 

When I just remove the test_workers property or when "enabled" is set to "false "everything works fine. 

you may see my test attempt in below repo. (there "test_workers"->"enabled" is true). You may change it to "false" and run again to see the difference.

https://github.com/dim912/nwruntb

steps to run sample
-----------------------
copy selenium.jar to root directory
npm install
node runner.js

selenium version => selenium-server-standalone-2.47.1.jar

Thank you.

**Comment by dim912** [comment]
By further debugging, found below 

In minimal configurations, nwrun pass below properties to runner method in nightwatch index.js. This works fine when test workers are disabled. But it fails when test workers are enabled.

config:__NWRUN_FAKED_CONFIG_BECAUSE_YOLO__0.838532
env:default                                       
c:__NWRUN_FAKED_CONFIG_BECAUSE_YOLO__0.83853264962
o:tests_output                                    
output:tests_output                               
r:junit                                           
reporter:junit                                    
e:default                                         
t:undefined                                       
test:undefined                                    
g:undefined                                       
group:undefined                                   
s:undefined                                       
skipgroup:undefined                               
f:                                                
filter:                                           
a:                                                
tag:                                              
h:undefined                                       
help:undefined                                    
v:undefined                                       
version:undefined                                 
                                                  
Noticed nightwatch provided CLI (the normal method of running nightwatch using nightwatch.json) pass only below parameters to runner method in nightwatch index.js, in the same scenario(provided above).

_:                                                 
config:./nightwatch.json                           
c:./nightwatch.json                                
output:tests_output                                
o:tests_output                                     
reporter:junit                                     
r:junit                                            
env:default                                        
e:default                                          
filter:                                            
f:                                                 
tag:                                               
a:                                                 
$0:C:\Program Files\nodejs\node.exe D:\workspaces\ 
_source:                                           

Work around 
--------------------------------------------

deleted 'test' property from argv object which is passed from nwrun -> spawn.js to runner method in nightwatch index.js, when test workers and enabled.

//added below three lines, just before calling nightwatch.runner in spawn.js of nwrun
      if (settings.test_workers && settings.test_workers.enabled) {
        delete argv['test']
      }

I believe this is not the perfect solution though it is working for my requirement.

**Comment by pateketrueke** [comment]
Awesome, so much thanks for your feedback! :beer:

I recently got on this issue too, but I just disabled the workers...

I'll try your fix and share whatever I found.

**Comment by dim912** [comment]
Hi pateketrueke. 

Hope you are doing good. Helpful if you could accept the pull request. Actually we are using nwrun to kick start nightwatch, with user selectable test settings(browser, environment... etc). With ourscope its a must run tests parallel, to optimize the time. We like to depend on original npm package of nwrun, rather than a custom nwrun(with this fix). :).  So helpful if you could accept the pull request and publish. 

Thank you..!

**Comment by pateketrueke** [comment]
Sorry for being late, already released `0.3.2` with your fix.

So much thanks for your feedback! 🎉
